import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SessionProv from "@/components/providers/SessionProv";
import { ToastProvider } from "@/components/providers/toaster-provider";

const inter = Inter({ subsets: ["latin"] });

import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProv>
          <main className="h-screen flex flex-col justify-center items-center">
            <ToastProvider />
            <Navbar />
            {children}
          </main>
        </SessionProv>
      </body>
    </html>
  );
}
